apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-backup-new-pvc-11-db
  namespace: {{ .Values.global.namespace }}

spec:
  accessModes:
    - ReadWriteMany

  storageClassName: {{ .Values.global.storageClassName }}

  volumeMode: Filesystem

  resources:
    requests:
      storage: 20Gi