apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data-new-pv-11

spec:
  capacity:
    storage: 10Gi

  volumeMode: Filesystem

  accessModes:
    - ReadWriteMany

  persistentVolumeReclaimPolicy: Retain

  storageClassName: azurefile

  claimRef:
    name: postgresql-data-new-pvc-11-db
    namespace: dbns

  nfs:
    path: /data/nfs/postgresql-data-new
    server: 127.0.0.1
