apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-backup-new-pv-11

spec:
  capacity:
    storage: 50Gi   # ✅ match backup PVC

  volumeMode: Filesystem

  accessModes:
    - ReadWriteMany

  persistentVolumeReclaimPolicy: Retain

  storageClassName: azurefile

  claimRef:
    name: postgresql-backup-new-pvc-11-db
    namespace: dbns

  nfs:
    path: /data/nfs/postgresql-backup-new
    server: 127.0.0.1
``